export const Colors = {
  BOLD_BLUE: '#2699FB',
  DARK_BLUE: '#007FEB',
  LIGHT_BLUE: '#41A0FC',
  WHITE: '#FFFFFF',
  WHITE_TEXT: '#FFFFFF',
  WHITE_TRANSPARENT: '#FFFFFF00',
  WHITE_HALF_TRANSPARENT: '#FFFFFFB0',
};
